# General Jekyll Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title.html

url: https://duncan.mac-vicar.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
collections:
  tutorials:
    output: true
    permalink: /tutorial/:title/index:output_ext
